/**
 * snapshot-live.mjs — take a LIVE snapshot of the running game process.
 *
 *   HB_WALLET=key.json node backend/native/snapshot-live.mjs
 *   HB_WALLET=key.json node backend/native/snapshot-live.mjs --reason "pre-roster redeploy"
 *
 * This is NOT the legacynet seed data, and the distinction matters enough to be
 * enforced rather than remembered.
 *
 * There are two very different bodies of player state in this repository:
 *
 *   * `legacy-players.json` — the 168 wallets recovered out of the dead AO
 *     legacynet checkpoints. It is committed, it is what `deploy.mjs` seeds by
 *     default, and it is the ORIGIN. It should never be overwritten by anything
 *     produced here, because it can only be regenerated by reviving nine dead
 *     processes, and a bad merge would quietly lose people who paid.
 *
 *   * a live snapshot — whatever the currently deployed process happens to hold
 *     right now, which is mostly test accounts and bot wallets on top of a
 *     restore of the above. It is a checkpoint, not a source.
 *
 * So every file this writes is stamped with `kind: "live-snapshot"`, the process
 * it came from, when, and WHY it was taken. Restoring is then a decision made
 * with the reason in front of you, and going back to the seed data is always
 * possible because nothing here ever touches it.
 *
 * Output: `backend/native/snapshots/<timestamp>-<pid>.json`
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { jwkToAddress, sendMessage } from './hbclient.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, '..', '..');
const OUT_DIR = path.join(HERE, 'snapshots');

const argv = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 ? argv[i + 1] : fallback;
};

function liveProcess() {
  const file = path.join(ROOT, 'live-process.txt');
  const [fileId, fileNode] = fs.existsSync(file)
    ? fs.readFileSync(file, 'utf8').trim().split(/\r?\n/).map((line) => line.trim())
    : [];
  const pid = process.env.GAME_PROCESS || fileId;
  if (!/^[A-Za-z0-9_-]{43}$/.test(String(pid ?? ''))) {
    throw new Error('set GAME_PROCESS, or write live-process.txt');
  }
  return { pid, node: process.env.NODE_URL || fileNode || 'https://schedule.forward.computer' };
}

function wallet() {
  const file = process.env.HB_WALLET || path.join(ROOT, 'arweave-wallet-DA9qhP25.json');
  if (!fs.existsSync(file)) throw new Error(`no keyfile at ${file}; set HB_WALLET`);
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

/**
 * Read a published key with a plain GET.
 *
 * No `accept: application/json`: that makes the node answer with its own
 * envelope and the value arrives as a string inside it. See the same note in
 * mint-worker.mjs — it is the difference between reading the process and
 * reading the node's opinion of the process.
 */
async function readKey(node, pid, key) {
  const res = await fetch(`${node}/${pid}~process@1.0/now/${key}`);
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`read ${key}: ${res.status}`);
  const text = (await res.text()).trim();
  // An HTML body at 200 is the node's own landing page, which is what a missing
  // published key looks like on some routes. Treat it as absent, never as data.
  if (!text || text === 'null' || text.startsWith('<')) return null;
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

const jwk = wallet();
const owner = await jwkToAddress(jwk);
const { pid, node } = liveProcess();
const reason = flag('reason', 'routine checkpoint');

console.log(`process ${pid}\nnode    ${node}\nowner   ${owner}\nreason  ${reason}\n`);

/**
 * Read the reply produced by one specific slot.
 *
 * Not `/now/results/output/data`: that is whatever the process computed LAST,
 * so a concurrent message answers for yours. Addressing the slot is the only
 * way to be certain the reply is the one you asked for. A slot that has not
 * been computed yet answers 404, which is a wait rather than a fault.
 */
async function readSlot(slotNumber, { attempts = 120, delayMs = 500 } = {}) {
  const url = `${node}/${pid}~process@1.0/compute&slot=${slotNumber}/results/output/data`;
  for (let i = 0; i < attempts; i += 1) {
    const res = await fetch(url).catch(() => null);
    if (res?.ok) {
      const text = (await res.text()).trim();
      if (text && !text.startsWith('<')) {
        try {
          return JSON.parse(text);
        } catch {
          return text;
        }
      }
    }
    await new Promise((r) => { setTimeout(r, delayMs); });
  }
  throw new Error(`slot ${slotNumber} never computed`);
}

/**
 * One owner-only page of the export.
 *
 * `Admin.EXPORT`, not `Admin.Snapshot`. They look interchangeable and are not:
 * `Admin.Snapshot` builds the admin CONSOLE's view, whose rows are deliberately
 * compact — a companion appears there as `name`, `level` and `status`, flattened
 * out of the record. Snapshotting through that door produced a 219-player file
 * containing zero companions, which `Admin.Load` would have restored as 219
 * players who own nothing. `Admin.Export` is the migration door and carries the
 * whole holding: roster, collection, activeId, monsterSeq and adopted.
 */
async function exportPage(offset, section) {
  const receipt = await sendMessage({
    node,
    jwk,
    process: pid,
    action: 'Admin.Export',
    tags: { Offset: String(offset), Limit: '25', ...(section ? { Section: section } : {}) },
  });
  const slot = Number(receipt?.slot ?? receipt?.headers?.slot);
  if (!Number.isFinite(slot)) {
    throw new Error(`Admin.Export was not scheduled: ${JSON.stringify(receipt).slice(0, 300)}`);
  }
  return readSlot(slot);
}

// Players, page by page. A page is retried rather than abandoned: treating an
// unreadable chunk as the end of the table is how a migration silently drops
// everyone after the first hiccup.
const players = [];
let firstPage = null;
for (let offset = 0; ; offset += 25) {
  let page = null;
  for (let attempt = 0; attempt < 4 && !page; attempt += 1) {
    page = await exportPage(offset).catch((e) => {
      console.log(`  page ${offset} attempt ${attempt + 1}: ${e.message}`);
      return null;
    });
  }
  if (!page) throw new Error(`page at offset ${offset} never read; refusing to write a partial snapshot`);
  firstPage = firstPage ?? page;
  players.push(...(page.players ?? []));
  console.log(`  players ${players.length}/${page.total ?? '?'}`);
  if (page.done || !(page.players ?? []).length) break;
}

// The market is its own section, and it MUST be carried: a listed companion is
// in `Market` and in nobody's collection, so an export that walks only players
// destroys the creatures inside the listings.
const listings = [];
let marketFirst = null;
for (let offset = 0; ; offset += 25) {
  const page = await exportPage(offset, 'market').catch(() => null);
  if (!page) break;
  marketFirst = marketFirst ?? page;
  listings.push(...(page.market ?? []));
  if (page.done || !(page.market ?? []).length) break;
}

const snapshot = {
  players,
  offerings: firstPage?.offerings,
  checkins: firstPage?.checkins,
  metrics: firstPage?.metrics,
  audit: firstPage?.audit,
  market: listings,
  marketSeq: marketFirst?.marketSeq,
  marketHistory: marketFirst?.marketHistory,
};
// Free reads that round out the picture. A snapshot that only had players would
// restore the accounts and silently drop the market and the registry.
const [assets, market, marketHistory, runeToken, users, factions] = await Promise.all([
  readKey(node, pid, 'assets'),
  readKey(node, pid, 'market'),
  readKey(node, pid, 'markethistory'),
  readKey(node, pid, 'runetoken'),
  readKey(node, pid, 'users'),
  readKey(node, pid, 'factions'),
]);

const stamp = new Date().toISOString().replace(/[:.]/g, '-');
const file = path.join(OUT_DIR, `${stamp}-${pid.slice(0, 12)}.json`);
fs.mkdirSync(OUT_DIR, { recursive: true });

const out = {
  // The stamp. Read this before restoring anything.
  kind: 'live-snapshot',
  isSeedData: false,
  note: 'A checkpoint of a running process. NOT the legacynet seed data — that '
    + 'is legacy-players.json, it is the origin, and nothing here replaces it. '
    + 'Restoring this on a fresh deploy layers these accounts ON TOP of the '
    + 'seeded 168; Admin.Load takes the max of every counter, so it cannot '
    + 'remove anything either way.',
  reason,
  takenAt: new Date().toISOString(),
  source: { process: pid, node, owner },
  seedDataOrigin: 'backend/native/legacy-players.json',
  counts: {
    players: players.length,
    // Counted from the EXPORTED rows, not from the published view: this is the
    // number that says whether the file is restorable. A snapshot whose players
    // carry no companions is a snapshot that erases everybody, and it looks
    // identical to a good one until the day it is loaded.
    withCompanions: players.filter((p) => (p.monsters && Object.keys(p.monsters).length)
      || (p.collection && Object.keys(p.collection).length) || p.monster).length,
    companions: players.reduce((n, p) => n
      + Object.keys(p.monsters ?? {}).length + Object.keys(p.collection ?? {}).length, 0),
    listings: listings.length,
    sales: Array.isArray(snapshot.marketHistory) ? snapshot.marketHistory.length : 0,
    assets: assets ? Object.keys(assets).length : 0,
    usersReported: users ?? null,
  },
  // `state` is the shape `Admin.Load` reads back, so a restore is this file's
  // `state` handed straight to it.
  state: {
    ...snapshot,
    assets,
    publishedMarket: market,
    runeToken,
    factions,
  },
};

fs.writeFileSync(file, `${JSON.stringify(out, null, 2)}\n`);
console.log(`players        ${out.counts.players}`);
console.log(`with companions ${out.counts.withCompanions}`);
console.log(`companions     ${out.counts.companions}`);
console.log(`listings       ${out.counts.listings}`);
console.log(`sales          ${out.counts.sales}`);
if (out.counts.players > 0 && out.counts.companions === 0) {
  console.log('\nWARNING: not one companion was exported. Restoring this would');
  console.log('leave every player owning nothing. Do not trust this file.');
}
console.log(`\nwrote ${path.relative(ROOT, file)}`);
console.log('tagged kind=live-snapshot, isSeedData=false — the seed data is untouched.');
